apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: builder-
              spec:
                ttlStrategy:
                  secondsAfterCompletion: 1800 # Time to live after the workflow is completed, regardless of its status (overrides secondsAfterSuccess and secondsAfterFailure).
                  secondsAfterSuccess: 120     # Time to live after workflow is successful
                  secondsAfterFailure: 300     # Time to live after workflow fails
                serviceAccountName: operate-workflow-sa
                entrypoint: build
                arguments:
                  parameters:
                    - name: repo_name
                      # the value will get overridden by event payload from test-dep
                      value: readinglist
                    - name: version
                      # the value will get overridden by event payload from test-dep
                      value: v0.0.1
                templates:
                  - name: build
                    inputs:
                      parameters:
                        - name: repo_name
                        - name: version
                    sidecars:
                      - name: dind
                        image: registry.localhost:5000/docker:dind
                        env:
                          - name: DOCKER_TLS_CERTDIR
                            value: ""
                        args:
                          - --insecure-registry=registry.localhost:5000
                        securityContext:
                          privileged: true
                        mirrorVolumeMounts: true
                    container:
                      image: registry.localhost:5000/docker:latest
                      env:
                        - name: DOCKER_HOST
                          value: tcp://localhost:2375
                      args: 
                        - /bin/sh
                        - -c
                        - |
                          set -e
                          echo "Setting up SSH keys"
                          mkdir -p /root/.ssh
                          cp /ssh-key/id_rsa /root/.ssh/id_rsa
                          chmod 600 /root/.ssh/id_rsa
                          ssh-keyscan git-server.git-server >> /root/.ssh/known_hosts
                          echo "Building repository {{inputs.parameters.repo_name}}"
                          git clone ssh://git@git-server.git-server/code-ecosystem/{{inputs.parameters.repo_name}}.git
                          cd {{inputs.parameters.repo_name}}
                          files_changed=$(git show --pretty="" --name-only)
                          ./scripts/build.sh registry.localhost:5000 {{inputs.parameters.repo_name}} {{inputs.parameters.version}}
                          cd ..
                          git clone ssh://git@git-server.git-server/code-ecosystem/cloud-deploy.git
                          cd cloud-deploy
                          git config --global user.email "version-updater@localhost"
                          git config --global user.name "Version Updater"
                          if [ "{{inputs.parameters.repo_name}}" = "readinglist" ]; then
                            if echo "$files_changed" | grep -qE '(cmd/web)'; then
                              sed -i 's|VERSION=.*|VERSION={{inputs.parameters.version}}|g' ./kustomize/{{inputs.parameters.repo_name}}-ui/dev/configmap.yaml
                              git add ./kustomize/{{inputs.parameters.repo_name}}-ui/dev/configmap.yaml
                            fi
                          fi
                          sed -i 's|VERSION=.*|VERSION={{inputs.parameters.version}}|g' ./kustomize/{{inputs.parameters.repo_name}}/dev/configmap.yaml
                          git add ./kustomize/{{inputs.parameters.repo_name}}/dev/configmap.yaml
                          git commit -m "Update {{inputs.parameters.repo_name}} to version {{inputs.parameters.version}}"
                          git push origin master

                      volumeMounts:
                        - name: git-ssh-key
                          mountPath: /ssh-key
                          readOnly: true

                    volumes:
                      - name: git-ssh-key
                        secret:
                          secretName: git-ssh-key
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.repo_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.version
              dest: spec.arguments.parameters.1.value