apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: teacherportal
spec:
  hosts:
  - "teacherportal.localhost"
  gateways:
  - teacherportal
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: teacherportal