apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice
  name: microservice
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: microservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - image: registry.localhost:5000/microservice:v0.0.1
        imagePullPolicy: IfNotPresent
        name: microservice
        envFrom:
        - configMapRef:
            name: microservice-config
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: 8080
        readinessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30