apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservice-monitor
  labels:
    app: microservice
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: microservice
  endpoints:
  - port: web