apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: microservice
spec:
  hosts:
  - "microservice.localhost"
  gateways:
  - microservice
  http:
  - route:
    - destination:
        port:
          number: 8080
        host: microservice