apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
  name: istio
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    path: ./cloud-components/kustomize/istio
    repoURL: https://github.com/intellizone/code-ecosystem.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}