apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:16-alpine
        name: postgres
        envFrom:
        - secretRef:
            name: db-secret
        ports:
        - protocol: TCP
          containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
        
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata